global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'outbox-application'
    static_configs:
      - targets: ['outbox-app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    basic_auth:
      username: 'admin'
      password: 'admin123' 